#!/usr/bin/python3
# -*- coding: utf-8 -*-

ALTERNATIVE = 'alternative'
BOTH = 'BOTH'
BTC = "BTC"
BTCUSDT = "BTCUSDT"
BUY = 'BUY'
CORRESPONDANCE_DICT = {INFO_C:"INFO", MEDIUM_C:"WARNING", HIGH_C: "ERROR"}
CURRENT_SIDE = 'current_side'
EMITTOR = 'towardsecolonomy@gmail.com'
EMITTOR_PASSWORD = 'ricqltndktzitayp'
ENTRY_PRICE = 'entryPrice'
ERROR = "ERROR"
ETH = "ETH"
ETHUSDT = "ETHUSDT"
FREE = 'free'
FROM = 'From'
HIGH_C = 3
INFO = "INFO"
INFO_C = 1
FUTURES = 'FUTURES'
LEVERAGE = 'leverage'
LONG = 'LONG'
MARK_PRICE = 'markPrice'
MARKET = 'MARKET'
MAX_RETRY = 5
MEDIUM_C = 2
NA = 'NA'
NO_C = 0
OUT = 'OUT'
PLAIN = 'plain'
PORT = 465
POSITION_AMT = 'positionAmt'
PRICE = 'price'
RECEIVERS = ['briceleal@hotmail.fr', 'axel.berthier3@gmail.com'] 
SELL = 'SELL'
SHORT = 'SHORT'
SIDE = 'side'
SPOT = 'SPOT'
STMP_URL = "smtp.gmail.com"
STOP_MARKET = 'STOP_MARKET'
STRATEGIES_FOLDER = "STRATEGIES/"
SUBJECT = 'Subject'
SYMBOL = 'symbol'
TAKE_PROFIT_MARKET = 'TAKE_PROFIT_MARKET'
TO = 'To'
TYPE = 'type'
UNDEFINED = 'UNDEFINED'
USDT = 'USDT'
WARNING = "WARNING"
WITHDRAW_AVAILABLE = 'withdrawAvailable'