

#!/usr/bin/python3
# -*- coding: utf-8 -*-
import os

GMAIL_PASSWORD_KEY = os.getenv('GMAIL_PASSWORD_KEY')
API_KEY_MASTER_SPOT_1 = os.getenv('API_KEY_MASTER_SPOT_1')
API_KEY_MASTER_SECRET_SPOT_1 = os.getenv('API_KEY_MASTER_SECRET_SPOT_1')
API_KEY_MASTER_FUTURES_1 = os.getenv('API_KEY_MASTER_FUTURES_1')
API_KEY_MASTER_SECRET_FUTURES_1 = os.getenv('API_KEY_MASTER_SECRET_FUTURES_1')
API_KEY_MASTER_SPOT_2 = os.getenv('API_KEY_MASTER_SPOT_2')
API_KEY_MASTER_SECRET_SPOT_2 = os.getenv('API_KEY_MASTER_SECRET_SPOT_2')
API_KEY_MASTER_FUTURES_2 = os.getenv('API_KEY_MASTER_FUTURES_2')
API_KEY_MASTER_SECRET_FUTURES_2 = os.getenv('API_KEY_MASTER_SECRET_FUTURES_2')